---
title: "BORIS_Video"
output: html_document
---

# load libraries
```{r}
library(pacman)
p_load(lubridate, data.table, tidyverse, dplyr, accelerateR)
```


# load video annotations and plot bat behaviors
```{r}
# change to the path to your exported files
path <- "../../../../Dropbox/MPI/Dechmann_Lab/Johannes/boris_files/ExportedData/"
files <- list.files(path, pattern = ".csv")

video_data <- data.frame()

i = 1
for(i in 1:length(files)){
  a <- data.table::fread(paste0(path, files[i]), header = TRUE)
  # which bats are active?
  paste0(a$Behavior, a$Subject) %>% table
  a <- a[order(a$Subject, a$Behavior, a$Time),]
  a_mlt <- data.frame(start = a$Time[a$Status == "START"],
                            stop = a$Time[a$Status == "STOP"],
                            behavior = a$Behavior[a$Status == "START"],
                            subject = a$Subject[a$Status == "START"])
  a_mlt$duration <- a_mlt$stop - a_mlt$start
  a_mlt$file <- files[i]
  
  p <- ggplot(a_mlt, aes(x = start, xend = stop, y = behavior, yend = behavior, 
                          col = behavior, group = subject))+
    geom_segment(size = 2)+facet_wrap(~subject)+ggtitle(files[i])
  print(p)
  
  video_data <- rbind(video_data, a_mlt)
}


```

There are a few cases of behaviors overlapping. You need to clean this up in BORIS.


# summarise behaviors in videos
```{r}
video_data %>% group_by(behavior, subject, file) %>% summarise(total_duration = sum(duration)) -> video_data_sum

ggplot(video_data_sum, aes(x = behavior %>% factor, y = total_duration, col = subject))+
  geom_point()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  facet_wrap(~file)

```


#Here are some ideas for data analysis: 
--- Do bats sleep more or less in groups?
Check videos to see which bats are associated with each other
```{r}




```



--- How synchronized are their behaviors?
```{r}
files <- unique(video_data$file)
bats <- unique(video_data$subject)

for(i in 1:length(files)){
  for(j in 1:length(bats)){
    b1 <- video_data[which(video_data$file == files[i] & video_data$subject == bats[j]),]
    b2 <- video_data[which(video_data$file == files[i] & video_data$subject == bats[j+1]),]
    
    # expand the data into behaviors for each individual for each frame
    b1_full <- data.frame()  
    k = 1
    for(k in 1:nrow(b1)){
      temp <- data.frame(time = seq(b1$start[k], b1$stop[k], by = 1/50),
                         subject = b1$subject[k],
                         behavior = b1$behavior[k])
      b1_full <- rbind(b1_full, temp)
    }
    
    b2_full <- data.frame()  
    k = 1
    for(k in 1:nrow(b2)){
      temp <- data.frame(time = seq(b2$start[k], b2$stop[k], by = 1/50),
                         subject = b2$subject[k],
                         behavior = b2$behavior[k])
      b2_full <- rbind(b2_full, temp)
    }
    
    
    plot(b1_full$time, b1_full$behavior %>% factor, ylim = c(0,7))
    points(b2_full$time, b2_full$behavior %>% factor %>% as.numeric +0.5, col = 2)
    
    b1_full <- b1_full[order(b1_full$time),]
    duplicated(b1_full$time)
    
    b2_full <- b2_full[order(b2_full$time),]
    
    b1_b2 <- left_join(b1_full, b2_full, "time")
    b1_b2$behavior.x.num <- b1_b2$behavior.x %>% factor %>% as.numeric()
    b1_b2$behavior.y.num <- b1_b2$behavior.y %>% factor %>% as.numeric()
    
    summary(b1_b2)
    
    # cross correlation function will tell us at what lag and how strongly correlated the behaviors are for a pair of individuals
    ccf(b1_b2$behavior.x.num, b1_b2$behavior.y.num)
    # the cross correlation function won't work until the behaviors are not overlapping within an individual
  }
}


```


