---
title: "BORIS Firetail ACC"
output: html_document
date: "2023-07-04"
---

```{r}
library(pacman)
p_load(lubridate, data.table, tidyverse, dplyr, accelerateR, roll, randomForest, xts)
```

# load acceleration data
```{r}
load("../../../../Dropbox/MPI/Phyllostomus/BORIS/boris_video_match.robj")
rm(heart)
rm(star)
rm(moon)
# bolt$time[1]

bolt1s <- bolt1s[order(bolt1s$time),]
bolt1s %>% tail
```
why does time not align?

```{r}
fbolt <- fread("../../../../ownCloud/Firetail/Phyllostomushastatus/Model_tag_PH_FC_01/individual_bolt-annotated-bursts.csv")
fbolt %>% tail
fbolt$`burst-start-timestamp` %>% diff %>% plot
fbolt$eobs_accelerations_raw %>% length %>% table
```

```{r}
which.min(abs(bolt$time[i] - fbolt$`burst-start-timestamp`))
which.min(abs(bolt1s$time[i] - fbolt$`burst-start-timestamp`))
```


```{r}
fbolt$behavior <- NA
for(i in 268071:nrow(fbolt)){
  idx <- which.min(abs(bolt$time - fbolt$`burst-start-timestamp`[i]))  
  bolt$behavior[idx:(idx+25)] %>% table -> t
  if(length(t) > 0){
    maxt <- names(t)[which.max(t)]
    fbolt$behavior[i] <- maxt
  }
}

```


```{r}
fbolt$behavior %>% table
```


```{r}
bolt <- fread("../../../../Dropbox/MPI/Phyllostomus/Fieldwork/Data/FlightCage/PH_FC_01.csv")
bolt <- bolt[,1:5]
# bolt <- fread("../../../../ownCloud - ehurme@ab.mpg.de@owncloud.gwdg.de/Firetail/Phyllostomushastatus/Model_tag_PH_FC_01/")
heart <- fread("../../../../Dropbox/MPI/Phyllostomus/Fieldwork/Data/FlightCage/PH_FC_02.csv")
heart <- heart[,1:5]
star <- fread("../../../../Dropbox/MPI/Phyllostomus/Fieldwork/Data/FlightCage/PH_FC_03.csv")
star <- star[,1:5]
# rm(star)
moon <- fread("../../../../Dropbox/MPI/Phyllostomus/Fieldwork/Data/FlightCage/PH_FC_04.csv")
moon <- moon[,1:5]


bolt$time <- dmy_hms(bolt$timestamp)
# bolt$id <- "bolt"
# bolt$sampling <- 50
heart$time <- dmy_hms(heart$timestamp)

star$time <- dmy_hms(star$timestamp)

moon$time <- dmy_hms(moon$timestamp)

```