---
title: "ACC"
output: html_document
date: '2022-04-01'
---

```{r}
library(pacman)
p_load(data.table, dplyr, ggplot2, lubridate)

```

# ACC specs
25 Hz
4G
8bit

```{r}
#acc <- fread("D:/TrackingDryseason/AJcave/movebankfiles/PH_ST_074_S1_acc.csv")
acc <- fread("C:/Users/ehumre/Dropbox/MPI/Phyllostomus/Fieldwork/Data/Tracking/DrySeason/AJcave/DDMT/PH_ST_080.csv")
acc <- fread("C:/Users/ehumre/Dropbox/MPI/Phyllostomus/Fieldwork/Data/FlightCage/PH_FC_01/PH_FC_01_S1.csv")
# acc <- fread("../../../../Dropbox/MPI/Phyllostomus/Fieldwork/Data/Tracking/DrySeason/AJcave/DDMT/")
# acc <- fread("../../../FlightCage/Test/PH_FC_05_S5.csv")
acc
acc$time <- dmy_hms(acc$timestamp)
acc$localtime <- acc$time - 5*3600
plot(acc$localtime, acc$`Battery (V)`)

```

```{r}
plot(acc$localtime, acc$`location-lat`)
idx <- which(is.na(acc$`location-lat`))
hour(acc$localtime[-idx]) 

```



```{r}
acc$time %>% diff %>% as.numeric %>% plot()
```


```{r}
# idx <- 1:
idx <- 41000:43000
idx <- 45000:100000
idx <- 1:nrow(acc)
with(acc[idx,], plot(time, X, type = "l", col = rgb(0,0,1,.2)))
with(acc, lines(time, Y, type = "l", col = rgb(1,0,0,.2)))
with(acc, lines(time, Z, type = "l", col = rgb(0,1,0,.2)))
```
