---
title: "Firetail Annotations"
output: html_document
date: "2022-10-17"
---
# load libraries
```{r}
pacman::p_load(data.table, tidyverse, dplyr, ggplot2, lubridate,
               janitor, zoo)
my_options <- options(digits.secs = 3) 
```



# clean and calculate overlap function
```{r}
ft_overlap <- function(ftm, ft){
  # clean
  require(magrittr)
  
  ftm$annotation_layer_commuting[ftm$annotation_layer_commuting == ""] <- NA
  ft$annotation_layer_commuting[ft$annotation_layer_commuting == ""] <- NA
  ftm$annotation_layer_foraging[ftm$annotation_layer_foraging == ""] <- NA
  ft$annotation_layer_foraging[ft$annotation_layer_foraging == ""] <- NA
  ftm$annotation_layer_resting[ftm$annotation_layer_resting == ""] <- NA
  ft$annotation_layer_resting[ft$annotation_layer_resting == ""] <- NA
  ftm$annotation_layer_unknown[ftm$annotation_layer_unknown == ""] <- NA
  ft$annotation_layer_unknown[ft$annotation_layer_unknown == ""] <- NA

  annotation_tally_ftm <- data.frame(commuting = NA, foraging = NA, resting = NA,
                                     total = NA, analysis = "annotation_tally_ftm")
  annotation_tally_ft <- data.frame(commuting = NA, foraging = NA, resting = NA,
                                    total = NA, analysis = "annotation_tally_ft")
  
  annotation_tally_ftm$commuting <- table(ftm$annotation_layer_commuting) %>% 
    na.omit %>% sum
  annotation_tally_ft$commuting <- table(ft$annotation_layer_commuting) %>% 
    na.omit %>% sum
  annotation_tally_ftm$foraging <- table(ftm$annotation_layer_foraging) %>% 
    na.omit %>% sum
  annotation_tally_ft$foraging <- table(ft$annotation_layer_foraging) %>% 
    na.omit %>% sum
  annotation_tally_ftm$resting <- table(ftm$annotation_layer_resting) %>% 
    na.omit %>% sum
  annotation_tally_ft$resting <- table(ft$annotation_layer_resting) %>% 
    na.omit %>% sum
  
  annotation_tally_ftm$total <- sum(annotation_tally_ftm[,1:3])
  annotation_tally_ft$total <- sum(annotation_tally_ft[,1:3])
  
  overlap_ftm_to_ft <- data.frame(commuting = NA, foraging = NA, resting = NA, 
                                  total = NA, analysis = "overlap_ftm_to_ft")
  overlap_ft_to_ftm <- data.frame(commuting = NA, foraging = NA, resting = NA,
                                  total = NA, analysis = "overlap_ft_to_ftm")
  
  overlap_ftm_to_ft$commuting <- round(sum(which(!is.na(ftm$annotation_layer_commuting)) %in%
    which(!is.na(ft$annotation_layer_commuting != "")))/annotation_tally_ftm$commuting[1], 3) *
    100
  overlap_ftm_to_ft$foraging <- round(sum(which(!is.na(ftm$annotation_layer_foraging)) %in%
    which(!is.na(ft$annotation_layer_foraging != "")))/annotation_tally_ftm$foraging[1], 3) * 
    100
  overlap_ftm_to_ft$resting <- round(sum(which(!is.na(ftm$annotation_layer_resting)) %in%
    which(!is.na(ft$annotation_layer_resting != "")))/annotation_tally_ftm$resting[1], 3) * 
    100
  
  overlap_ft_to_ftm$commuting <- round(sum(which(!is.na(ft$annotation_layer_commuting)) %in%
    which(!is.na(ftm$annotation_layer_commuting != "")))/annotation_tally_ft$commuting[1], 3) *
    100
  overlap_ft_to_ftm$foraging <- round(sum(which(!is.na(ft$annotation_layer_foraging)) %in%
    which(!is.na(ftm$annotation_layer_foraging != "")))/annotation_tally_ft$foraging[1], 3) *
    100
  overlap_ft_to_ftm$resting <- round(sum(which(!is.na(ft$annotation_layer_resting)) %in%
    which(!is.na(ftm$annotation_layer_resting != "")))/annotation_tally_ft$resting[1], 3) *
    100
  
  return(rbind(annotation_tally_ftm, annotation_tally_ft, overlap_ftm_to_ft, overlap_ft_to_ftm))
}
```

#Compare two models on the same bat
## 7CDB4A2
```{r}
ftm <- fread("../../../../ownCloud/Firetail/Model_7CE02AF_main/7CDB4A2/individual_7CDB4A2-annotated-bursts-gps.csv") %>% clean_names

ft <- fread("../../../../ownCloud/Firetail/Model_7CDB4A2/7CDB4A2/individual_7CDB4A2-annotated-bursts-gps.csv") %>% clean_names

ft_overlap(ftm, ft)
```

## 7CDBB60
```{r}
ftm <- fread("../../../../ownCloud/Firetail/Model_7CE02AF_main/7CDBB60/individual_7CDBB60-annotated-bursts-gps.csv") %>% clean_names

ft <- fread("../../../../ownCloud/Firetail/Model_7CDB4A2/7CDBB60/individual_7CDBB60-annotated-bursts-gps.csv") %>% clean_names

ft_overlap(ftm, ft)
```

## 7CE02AF
```{r}
ftm <- fread("../../../../ownCloud/Firetail/Model_7CE02AF_main/7CE02AF/individual_7CE02AF-annotated-bursts-gps.csv") %>% clean_names

ft <- fread("../../../../ownCloud/Firetail/Model_7CDB4A2/7CE02AF/individual_7CE02AF-annotated-bursts-gps.csv") %>% clean_names

ft_overlap(ftm, ft)
```


# how does the same model group SOM groupings by behavior between bats?
## does l1-01 always show the same pattern?
```{r}
bats <- list.dirs(path = "../../../../ownCloud/Firetail/Model_7CE02AF_main/")
firetail_annotations <- data.frame()
firetail_ann_freq <- data.frame()
i = 19
for(i in 2:length(bats)){
  files <- list.files(bats[i], full.names = TRUE)
  idx <- grep(pattern = "annotated-bursts-gps.csv", files)
  if(length(idx) == 0){idx <- grep(pattern = "annotated-burst-gps.csv", files)}
  ft <- fread(files[idx]) %>% clean_names()
  SOMs <- c(ft$annotation_layer_commuting %>% unique, 
            ft$annotation_layer_foraging %>% unique, 
            ft$annotation_layer_resting %>% unique) %>% unique
  try({
    SOMs <- c(SOMs, ft$annotation_layer_unknown) %>% unique
  })
  SOMs <- SOMs[order(SOMs)]
  # frequency of events
  df <- data.frame(matrix(ncol = length(SOMs), nrow = 1))
  colnames(df) <- c("bat", SOMs[2:length(SOMs)])
  bat <- substr(bats[i], start = nchar(bats[i])-6, stop = nchar(bats[i]))
  df$bat[1] <- bat
  db <- df # behavioral class of SOMs
  
  commuting <- table(ft$annotation_layer_commuting)
  foraging <- table(ft$annotation_layer_foraging) 
  resting <- table(ft$annotation_layer_resting) 
  try({unknown <- table(ft$annotation_layer_unknown)}) 
  j = 2
  for(j in 1:length(commuting)){
    ID <- {}
    idx <- {}
    ID <- names(commuting[j])
    idx <- which(names(df) == ID)
    df[1,idx] <- commuting[j]
    db[1,idx] <- "commuting"
  }
  for(j in 1:length(foraging)){
    ID <- {}
    idx <- {}
    ID <- names(foraging[j])
    idx <- which(names(df) == ID)
    df[1,idx] <- foraging[j]
    db[1,idx] <- "foraging"
  }
  for(j in 1:length(resting)){
    ID <- {}
    idx <- {}
    ID <- names(resting[j])
    idx <- which(names(df) == ID)
    df[1,idx] <- resting[j]
    db[1,idx] <- "resting"
  }
  try({
    for(j in 1:length(unknown)){
      ID <- {}
      idx <- {}
      ID <- names(unknown[j])
      idx <- which(names(df) == ID)
      df[1,idx] <- unknown[j]
      db[1,idx] <- "unknown"
  }
  })
  firetail_annotations <- rbindlist(list(firetail_annotations, db), fill = TRUE)
  firetail_ann_freq <- rbindlist(list(firetail_ann_freq, df), fill = TRUE)
}
```

# how do behavioral groups agree? 
```{r}
myfreq <- sapply(firetail_annotations, function(x) table(factor(x, levels=unique(unlist(firetail_annotations))[c(25,26,27,29)], ordered=TRUE)))

myfreq#/24 %>% round(.,2)
```
# majority rule
```{r}
i = 2
SOM_majority <- data.frame(SOM = rep(NA, 25), behav = NA)
for(i in 2:ncol(myfreq)){
  SOM_majority$SOM[i-1] <- colnames(myfreq)[i]
  SOM_majority$behav[i-1] <-  names(which.max(myfreq[,i]))  
}

```


```{r}
firetail_ann_freq[,2:26] %>% colMeans(na.rm = TRUE)
firetail_ann_freq[,2:26]/rowSums(firetail_ann_freq[,2:26], na.rm = TRUE) -> temp

temp_mlt <- melt(temp)
ggplot(temp_mlt, aes(variable, value))+geom_violin()
```


# HMM to model transition probability matrix for all individuals
```{r}
library(pacman)
p_load(mHMMbayes)
```

