---
title: "FPT Foraging Sites"
output: html_document
---

Exploring FPT to identify foraging sites

HMM didn't work well when attempting to regularize the data

# load libraries
```{r}
library(pacman)

p_load("momentuHMM", "lubridate", "data.table", "zoo", "move", "dplyr", "adehabitatLT", mixtools, ggplot2, latticeExtra)

# source("../../../movebank_login.R")

proj.ll <- CRS('+proj=longlat +datum=WGS84 +no_defs')
projUTM <- CRS("+proj=utm +zone=17 +ellps=GRS80 +datum=NAD83 +units=m +no_defs")
```

# load data
```{r}
load("../../../../Dropbox/MPI/Phyllostomus/Fieldwork/Data/results_part1.rdata")
load("../../../../Dropbox/MPI/Phyllostomus/Fieldwork/Data/phastmove.rdata")
inf <- read.delim("../../../../Dropbox/MPI/Phyllostomus/Fieldwork/Data/Greater spear-nosed bat (Phyllostomus hastatus) in Bocas del Toro 2021-2022-reference-data.csv", header=T, sep=',', as.is=T)
```

# get technosmart data
```{r}
ajcave <- "D:/TrackingDryseason/AJcave/movebankfiles"
gps_files <- list.files(path = ajcave, pattern = "*gps*", full.names = TRUE)

aj <- data.table()
for(i in 1:length(gps_files)){
  aj_tag <- fread(gps_files[i])  
  aj <- rbind(aj, aj_tag, fill = TRUE)
}

aj$time <- aj$Timestamp %>% dmy_hms

plot(aj$location.lon, aj$location.lat, asp = 1, col = as.factor(aj$TagID))

```


# Create traj  
```{r}
# plot(phast)
# phast <- phast[phast$location_long > -90,]
# df <- as.data.frame(phast)

df <- aj
df$location_lat <-  df$location.lat
df$location_long <- df$location.lon


po <- spTransform(SpatialPoints(df[,c("location_long", "location_lat")], proj4string=proj.ll), CRSobj=projUTM)
df$y <- po@coords[,2]
df$x <- po@coords[,1]

df$date <- date(df$time)
df$ID <- paste0(df$TagID, "_", df$date)

p.traj <- as.ltraj(data.frame(X = df$x, Y = df$y), date = df$time, id = factor(df$TagID), burst = df$ID)
pj <- ld(p.traj)

```

# First Passage Time

```{r}
# Determine Optimal Radius
radii <- seq(15, 300, by = 15)
fpts <- fpt(p.traj, radii, units = "seconds")

varfpt <- varlogfpt(fpts, graph = F)
names(varfpt) <- radii

Radius <- as.numeric(names(which.max(colMeans(as.matrix(varfpt), na.rm = TRUE))))

```

### plot radius
```{r}
boxplot(varfpt, ylab = 'Variance of log(FPT)', xlab = 'Radius (m)', main = paste0("Radius = ", Radius, " m"))
abline(v = which(radii == Radius), col = 2)
```


```{r}
fpt_mean <- colMeans(as.matrix(varfpt), na.rm = TRUE)
fpt_se <- {}
for(i in 1:ncol(varfpt)){
  fpt_se[i] <- sd(varfpt[,i], na.rm = TRUE)# /sqrt(length(na.omit(varfpt[,i])))
}
fpt_rad <- data.frame(fpt_mean, fpt_se, radii)
```

### plot fpt radius
```{r}
p <- ggplot(fpt_rad, aes(x = radii, y = fpt_mean))+geom_line()+ 
  geom_errorbar(aes(ymin=fpt_mean-fpt_se, ymax=fpt_mean+fpt_se), width=30, colour = "black") + 
  geom_line() + theme_classic() + xlab("FPT Radius (m)") + ylab("Mean variance (SD)") +
  geom_segment(aes(x = 0, y = max(colMeans(as.matrix(varfpt), na.rm = TRUE)), xend = Radius, yend = max(colMeans(as.matrix(varfpt), na.rm = TRUE))), linetype = "dashed") +
  geom_segment(aes(x = Radius, y = 0, xend = Radius, yend = max(colMeans(as.matrix(varfpt), na.rm = TRUE))), linetype = "dashed") +
  scale_x_continuous(expand = c(0,0)) + scale_y_continuous(expand = c(0,0)) 
p + theme(plot.margin = unit(c(1,1,1,1), "cm"))
# ggpubr::ggarrange(p + theme(plot.margin = unit(c(1,1,1,1), "cm")), labels = "A")
```

### Determine threshold
```{r}
fpt <- unlist(fpt(p.traj, Radius, units = "seconds"))
logfpts <- na.omit(log(fpt))
mixmdl <- mixtools::normalmixEM(logfpts, k = 3)
plot(mixmdl,which=2)
lines(density(logfpts), lty=2, lwd=2)
abline(v = mixmdl$mu)
idx <- 2#which.min(mixmdl$mu)
#2.58 99% CI
#1.96 95% CI

threshold <- mixmdl$mu[idx]+1.96*mixmdl$sigma[idx]
abline(v = threshold, col = 2, lwd = 2, lty = 2)
exp(threshold)
```

### Match FPT data
```{r}
Bats <- {}
for(i in 1:length(p.traj)){
  # layout(cbind(c(1,2), c(3,4), c(5,6)))
  bat <- ld(p.traj[i])
  bat$bat <- burst(p.traj[i])
  fpts <- unlist(fpt(p.traj[i], Radius))
  bat$FPT <- fpts
  bat$FPT01 <- as.numeric(fpts > exp(threshold))
  Bats <- rbind(Bats, bat)
}

Split <- strsplit(as.character(Bats$bat), "_", fixed = TRUE)
Bats$id <- sapply(Split, "[", 1)

summary(Bats)

```
# plot tracks
```{r}

IDs <- unique(Bats$burst)
i = 14

for(i in 1:length(IDs)){
  b <- Bats[which(Bats$burst == IDs[i]),]
  # plot(b$x, b$y, col = b$FPT01+1,
  #      asp = 1)

  p <- ggplot(b, aes(x, y, col = log(FPT)))+geom_path()+
    geom_point(aes(size = FPT), shape = 21)+ ggtitle(IDs[i])+
    viridis::scale_color_viridis()+theme_minimal()+
    ylim(c(min(Bats$y),max(Bats$y)))+
    xlim(c(min(Bats$x),max(Bats$x)))
  print(p)

  # ggplot(b[30:100,], aes(x,y,col = FPT))+geom_tile

}

```
# plot level plot FPT
```{r}

# create data
set.seed(1) 
data <- data.frame(x = rnorm(100), y = rnorm(100)) 
data$z <- with(data, x * y + rnorm(100, sd = 1)) 
 
# showing data points on the same color scale 
levelplot(z ~ x * y, data, 
          panel = panel.levelplot.points, cex = 1.2
    ) + 
    layer_(panel.2dsmoother(..., n = 200))

Bats$FPT %>% hist(breaks = 500, xlim = c(0,500))
levelplot(FPT~x*y, data = Bats[Bats$FPT > 200 & Bats$x > 350000,],
          panel = panel.levelplot.points, cex = 1)+
  layer_(panel.2dsmoother(...,n = 200))



```
# rasterize FPT
```{r}
###############################
# rasterize points
###############################
high_fpt <- Bats[which(Bats$FPT > 100),] # & Bats$x < 350000),]

r <- raster(ncols=1000, nrows=1000)
r <- projectExtent(r, projUTM)
extent(r) <- extent(min(high_fpt$x, na.rm = TRUE)-500, 
                    max(high_fpt$x, na.rm = TRUE)+500, 
                    min(high_fpt$y, na.rm = TRUE)-500, 
                    max(high_fpt$y, na.rm = TRUE)+500)
xy <- cbind(high_fpt$x, high_fpt$y)
r
fpt <- rasterize(xy, r, high_fpt$FPT, fun=sum)
plot(fpt)
FPT <- projectRaster(fpt, crs = proj.ll)
plot(FPT)
values(FPT) <- log(values(FPT))
```

```{r}
# devtools::install_github("ropensci/rnaturalearthhires")
p_load(archdata, sp, leaflet, rgdal, rgeos, spatstat, rworldmap, 
       ggmap, gstat, leaflet, mapview, raster, rnaturalearth, rnaturalearthdata)

```


```{r}
panama <- ne_countries(country = "Panama", scale = 10)
panama <- ne_states(country = "Panama")
bocas <- panama[panama$name == "Bocas del Toro",]
```


```{r}
m1 <- mapview(bocas, color = "gray10", alpha.regions = 0)

spplot(FPT)
fpt_contour <- rasterToContour(FPT, nlevels = 5)

names(df)
p_spat <-  SpatialPointsDataFrame(coords = df[,c("location_long", "location_lat")], 
                                  data = df,
                                  #data = df[,c(1,7,9,11:15,17,30,40)], 
                                   proj4string = proj.ll)
plot(p_spat)
```

```{r}

m2 <- mapview(p_spat, alpha.regions = 0.1)
m3 <- mapview(FPT, alpha.regions = 0.50, na.color = "transparent")
m4 <- mapview(fpt_contour, lwd = 0.5, color = "gray40")
m3

```



```{r}
values(FPT) %>% hist

idx <- which(values(FPT) > 10)
xy <- coordinates(FPT)[idx,] %>% unique
long_bouts <-  SpatialPointsDataFrame(coords = xy, 
                                      data = as.data.frame(xy),
                                   proj4string = proj.ll)
m5 <- mapview(long_bouts, color = "red", alpha.regions = 0.2)
m5
```

