---
title: "Firetail_ACC"
output: html_document
date: "2022-09-16"
---

```{r}
pacman::p_load(data.table, tidyverse, dplyr, ggplot2, lubridate,
               janitor, zoo)
my_options <- options(digits.secs = 3) 
```

```{r}
load("../../../../Dropbox/MPI/Phyllostomus/DDMT/DDMT_export/PH_ST_18/Filename_continuous_export_split#1_4.robj")
# ft <- fread("../../../../Dropbox/MPI/Phyllostomus/Firetail/Model_7CDB4A2/7CDB4A2/individual_7CDB4A2-annotated-samples.csv") %>% clean_names
fta <- fread("../../../../ownCloud/Firetail/Model_7CE02AF_main/7CDB4A2/individual_7CDB4A2-annotated-bursts-gps.csv")
```


```{r}
with(df[100000:750000,], #[73000:74000,], #[60000:120000,], 
     plot(datetime, acc_z+2, type = "o",
          cex = 0.1,
          ylim = c(-1,5), col = rgb(0,0,0,.5)))
lines(df$datetime, df$ve_dba, cex = .1, col = rgb(0,0.1,1,.5), type = "o")
points(f$datetime[f$marked_event == 1], 
       y = rep(1, length(which(f$marked_event == 1))), 
       col = 2,
       cex = 1)
```

```{r}

with(df[100000:500000,], #[60000:120000,], 
     plot(datetime+3600, acc_z+2, type = "o",
          cex = 0.1,
          ylim = c(-1,5), col = rgb(0,0,0,.1)))
# with(ft, points(burst_start_timestamp, layer %>% factor, 
#                         col = layer %>% factor))
points(fta$timestamp, y = as.numeric(!(fta$resting == "")), col = 4)
points(f$datetime[f$marked_event == 1]+3600, 
       rep(0, length(which(f$marked_event == 1))), 
       col = rgb(1,0,0,.4))
```

# find all wing pauses and see if it occurs exclusively during foraging
## recalc rle
```{r}
r <- rle(df$marked_event)
r$lengths[which(r$values == 1)] %>% hist(breaks = 100, xlim = c(0,70))
```

## investigate marked events
```{r}
r$lengths[4]
i = 42
for(i in 1:80){#length(r$lengths)){
  if(r$values[i] == 1){
      start <- {}
      end <- {}
      try(start <- sum(r$lengths[1:(i-1)])+1)
      if(i == 1) start <- 1
      end <- sum(r$lengths[1:i])
      tt <- f$marked_event[start:end] %>% table
      buff <- 100
      
      with(f[(start-buff):(end+buff),], 
           plot(datetime, acc_z, type = "l", ylim = c(-4,4),
                main = paste0(f$datetime[start], ", N = ", length(start:end))))
      with(f[(start-buff):(end+buff),], lines(datetime, acc_z, col = 2))
      with(f[(start-buff):(end+buff),], lines(datetime, acc_y, col = 5))
      with(f[(start-buff):(end+buff),], lines(datetime, ve_dba, col = 3))
      with(f[(start-buff):(end+buff),], lines(datetime, ve_sba_smoothed, col = 4))
      points(fta$timestamp-3600, y = as.numeric(!(fta$foraging == "")), type = "o")
      abline(v = f$datetime[start], lty = 2)
      abline(v = f$datetime[end], lty = 2)
      legend("topleft", col = c(1:4), 
             legend = c("Z", "Z_sm", "VeDBA", "VeDBA_sm"), 
             lty = 1, cex = .75)
      
      summary(f[start:end,])
    }
  }

```

```{r}

with(ft[1:10000,], plot(timestamp, annotation_layer_flying %>% as.factor))
with(ft[1:10000,], plot(timestamp, annotation_layer_commuting %>% as.factor))
with(ft[1:10000,], plot(timestamp, annotation_layer_perching %>% as.factor))


```

